export function createTypesTemplateContents(params: {
  typesEntryPath: string;
  normalizedProvideName: string;
}): string {
  const { typesEntryPath, normalizedProvideName } = params;

  return `// Auto-generated by @alikhalilll/nuxt-crypto
import type { CryptoService } from '${typesEntryPath}';

declare module '#app' {
  interface NuxtApp {
    $${normalizedProvideName}: CryptoService;
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $${normalizedProvideName}: CryptoService;
  }
}

export {};
`;
}
