/**
 * Generate the runtime type augmentation pointing `$<provideName>` at our
 * public `ApiProviderClient` type, so consumers get full IntelliSense on
 * `useNuxtApp().$apiProvider` and in component templates.
 */
export function createTypesTemplateContents(params: {
  typesEntryPath: string;
  normalizedProvideName: string;
}): string {
  const { typesEntryPath, normalizedProvideName } = params;

  return `// Auto-generated by @alikhalilll/nuxt-api-provider
import type { ApiProviderClient, RequestContext, ResponseContext, ApiError } from '${typesEntryPath}';

declare module '#app' {
  interface NuxtApp {
    $${normalizedProvideName}: ApiProviderClient;
  }
}

declare module 'vue' {
  interface ComponentCustomProperties {
    $${normalizedProvideName}: ApiProviderClient;
  }
}

declare module '#build/api-provider-handlers.mjs' {
  export function onRequestHandler(ctx: RequestContext): void | RequestContext | Promise<void | RequestContext>;
  export function onSuccessHandler<T = unknown>(ctx: ResponseContext<T>): void | Promise<void>;
  export function onErrorHandler(error: ApiError, ctx: RequestContext): void | Promise<void>;
}

export {};
`;
}
